# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/shadowsocks/config.proto

require 'google/protobuf'

require_relative Dir.pwd + '/' + 'common/net/network_pb'
require_relative Dir.pwd + '/' + 'common/protocol/user_pb'
require_relative Dir.pwd + '/' + 'common/protocol/server_spec_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proxy/shadowsocks/config.proto", :syntax => :proto3) do
    add_message "xray.proxy.shadowsocks.Account" do
      optional :password, :string, 1
      optional :cipher_type, :enum, 2, "xray.proxy.shadowsocks.CipherType"
      optional :iv_check, :bool, 3
    end
    add_message "xray.proxy.shadowsocks.ServerConfig" do
      repeated :users, :message, 1, "xray.common.protocol.User"
      repeated :network, :enum, 2, "xray.common.net.Network"
    end
    add_message "xray.proxy.shadowsocks.ClientConfig" do
      repeated :server, :message, 1, "xray.common.protocol.ServerEndpoint"
    end
    add_enum "xray.proxy.shadowsocks.CipherType" do
      value :UNKNOWN, 0
      value :AES_128_GCM, 5
      value :AES_256_GCM, 6
      value :CHACHA20_POLY1305, 7
      value :XCHACHA20_POLY1305, 8
      value :NONE, 9
    end
  end
end

module Xray
  module Proxy
    module Shadowsocks
      Account = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.proxy.shadowsocks.Account").msgclass
      ServerConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.proxy.shadowsocks.ServerConfig").msgclass
      ClientConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.proxy.shadowsocks.ClientConfig").msgclass
      CipherType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.proxy.shadowsocks.CipherType").enummodule
    end
  end
end
