# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/stats/config.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("app/stats/config.proto", :syntax => :proto3) do
    add_message "xray.app.stats.Config" do
    end
    add_message "xray.app.stats.ChannelConfig" do
      optional :Blocking, :bool, 1
      optional :SubscriberLimit, :int32, 2
      optional :BufferSize, :int32, 3
    end
  end
end

module Xray
  module App
    module Stats
      Config = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.app.stats.Config").msgclass
      ChannelConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.app.stats.ChannelConfig").msgclass
    end
  end
end
