# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/net/address.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("common/net/address.proto", :syntax => :proto3) do
    add_message "xray.common.net.IPOrDomain" do
      oneof :address do
        optional :ip, :bytes, 1
        optional :domain, :string, 2
      end
    end
  end
end

module Xray
  module Common
    module Net
      IPOrDomain = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.common.net.IPOrDomain").msgclass
    end
  end
end
