# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/net/destination.proto

require 'google/protobuf'

require_relative Dir.pwd + '/' + 'common/net/network_pb'
require_relative Dir.pwd + '/' + 'common/net/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("common/net/destination.proto", :syntax => :proto3) do
    add_message "xray.common.net.Endpoint" do
      optional :network, :enum, 1, "xray.common.net.Network"
      optional :address, :message, 2, "xray.common.net.IPOrDomain"
      optional :port, :uint32, 3
    end
  end
end

module Xray
  module Common
    module Net
      Endpoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.common.net.Endpoint").msgclass
    end
  end
end
