# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/net/network.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("common/net/network.proto", :syntax => :proto3) do
    add_message "xray.common.net.NetworkList" do
      repeated :network, :enum, 1, "xray.common.net.Network"
    end
    add_enum "xray.common.net.Network" do
      value :Unknown, 0
      value :RawTCP, 1
      value :TCP, 2
      value :UDP, 3
      value :UNIX, 4
    end
  end
end

module Xray
  module Common
    module Net
      NetworkList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.common.net.NetworkList").msgclass
      Network = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.common.net.Network").enummodule
    end
  end
end
