# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/net/port.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("common/net/port.proto", :syntax => :proto3) do
    add_message "xray.common.net.PortRange" do
      optional :From, :uint32, 1
      optional :To, :uint32, 2
    end
    add_message "xray.common.net.PortList" do
      repeated :range, :message, 1, "xray.common.net.PortRange"
    end
  end
end

module Xray
  module Common
    module Net
      PortRange = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.common.net.PortRange").msgclass
      PortList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.common.net.PortList").msgclass
    end
  end
end
