# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/serial/typed_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("common/serial/typed_message.proto", :syntax => :proto3) do
    add_message "xray.common.serial.TypedMessage" do
      optional :type, :string, 1
      optional :value, :bytes, 2
    end
  end
end

module Xray
  module Common
    module Serial
      TypedMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.common.serial.TypedMessage").msgclass
    end
  end
end
