# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/vmess/account.proto

require 'google/protobuf'

require_relative Dir.pwd + '/' + 'common/protocol/headers_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proxy/vmess/account.proto", :syntax => :proto3) do
    add_message "xray.proxy.vmess.Account" do
      optional :id, :string, 1
      optional :alter_id, :uint32, 2
      optional :security_settings, :message, 3, "xray.common.protocol.SecurityConfig"
      optional :tests_enabled, :string, 4
    end
  end
end

module Xray
  module Proxy
    module Vmess
      Account = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.proxy.vmess.Account").msgclass
    end
  end
end
