# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proxyman/command/command.proto

require 'google/protobuf'

require_relative Dir.pwd + '/' + 'common/protocol/user_pb'
require_relative Dir.pwd + '/' + 'common/serial/typed_message_pb'
require_relative Dir.pwd + '/' + 'core/config_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("app/proxyman/command/command.proto", :syntax => :proto3) do
    add_message "xray.app.proxyman.command.AddUserOperation" do
      optional :user, :message, 1, "xray.common.protocol.User"
    end
    add_message "xray.app.proxyman.command.RemoveUserOperation" do
      optional :email, :string, 1
    end
    add_message "xray.app.proxyman.command.AddInboundRequest" do
      optional :inbound, :message, 1, "xray.core.InboundHandlerConfig"
    end
    add_message "xray.app.proxyman.command.AddInboundResponse" do
    end
    add_message "xray.app.proxyman.command.RemoveInboundRequest" do
      optional :tag, :string, 1
    end
    add_message "xray.app.proxyman.command.RemoveInboundResponse" do
    end
    add_message "xray.app.proxyman.command.AlterInboundRequest" do
      optional :tag, :string, 1
      optional :operation, :message, 2, "xray.common.serial.TypedMessage"
    end
    add_message "xray.app.proxyman.command.AlterInboundResponse" do
    end
    add_message "xray.app.proxyman.command.AddOutboundRequest" do
      optional :outbound, :message, 1, "xray.core.OutboundHandlerConfig"
    end
    add_message "xray.app.proxyman.command.AddOutboundResponse" do
    end
    add_message "xray.app.proxyman.command.RemoveOutboundRequest" do
      optional :tag, :string, 1
    end
    add_message "xray.app.proxyman.command.RemoveOutboundResponse" do
    end
    add_message "xray.app.proxyman.command.AlterOutboundRequest" do
      optional :tag, :string, 1
      optional :operation, :message, 2, "xray.common.serial.TypedMessage"
    end
    add_message "xray.app.proxyman.command.AlterOutboundResponse" do
    end
    add_message "xray.app.proxyman.command.Config" do
    end
  end
end

module Xray
  module App
    module Proxyman
      module Command
        AddUserOperation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.app.proxyman.command.AddUserOperation").msgclass
        RemoveUserOperation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.app.proxyman.command.RemoveUserOperation").msgclass
        AddInboundRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.app.proxyman.command.AddInboundRequest").msgclass
        AddInboundResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.app.proxyman.command.AddInboundResponse").msgclass
        RemoveInboundRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.app.proxyman.command.RemoveInboundRequest").msgclass
        RemoveInboundResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.app.proxyman.command.RemoveInboundResponse").msgclass
        AlterInboundRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.app.proxyman.command.AlterInboundRequest").msgclass
        AlterInboundResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.app.proxyman.command.AlterInboundResponse").msgclass
        AddOutboundRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.app.proxyman.command.AddOutboundRequest").msgclass
        AddOutboundResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.app.proxyman.command.AddOutboundResponse").msgclass
        RemoveOutboundRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.app.proxyman.command.RemoveOutboundRequest").msgclass
        RemoveOutboundResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.app.proxyman.command.RemoveOutboundResponse").msgclass
        AlterOutboundRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.app.proxyman.command.AlterOutboundRequest").msgclass
        AlterOutboundResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.app.proxyman.command.AlterOutboundResponse").msgclass
        Config = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.app.proxyman.command.Config").msgclass
      end
    end
  end
end
