# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/protocol/user.proto

require 'google/protobuf'

require_relative Dir.pwd + '/' + 'common/serial/typed_message_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("common/protocol/user.proto", :syntax => :proto3) do
    add_message "xray.common.protocol.User" do
      optional :level, :uint32, 1
      optional :email, :string, 2
      optional :account, :message, 3, "xray.common.serial.TypedMessage"
    end
  end
end

module Xray
  module Common
    module Protocol
      User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.common.protocol.User").msgclass
    end
  end
end
